### ISSUE TITLE
Becomes unresponsive after I submit a simple python query

### ISSUE THREAD

**Issue by apoorvpandey0** [akashgp09/Online-Compiler-Web#1]
I cloned the app
then i did `npm install`
then I did `npm start`
The project opens up but becomes unresponsive as I submit the code.

**Comment by akashgp09** [comment]
Hi @apoorvpandey0 ! Thanks for reporting the issue. I have fixed this now in PR #2. You can pull the changes to your local and try again :)

Also don't forget to add your API key in this two places: [#L47](https://github.com/akashgp09/Online-Compiler-Web/blob/9b58a6cc826dcffce624b3dbd65ef1262cfc578e/src/Components/Compiler/Compiler.js#L47)  [#L80](https://github.com/akashgp09/Online-Compiler-Web/blob/9b58a6cc826dcffce624b3dbd65ef1262cfc578e/src/Components/Compiler/Compiler.js#L80)

**Comment by akashgp09** [comment]
Closing this issue.
Please re-open if you still have the problem.
